---
- hosts: '{{ target_host | default("localhost") }}'

  roles:
    - role: system
    - role: packages
    - role: docker
      when: with_docker
    - role: storage
      when: with_storage
    - role: configs
    - role: keyd # need config file linked to .config/keyd
      when: with_keyd
    - role: syncthing # needs config files copied/linked to .local/state/syncthing
      when: with_syncthing
    - role: wireguard
      when: with_wireguard

  pre_tasks:
    - import_tasks: tasks/platform.yml
    - import_tasks: tasks/rpi.yml