---
- include_tasks: install-arch.yml
  when: ansible_os_family == 'Archlinux'
- include_tasks: install-redhat.yml
  when: ansible_os_family == 'RedHat'
- include_tasks: install-debian.yml
  when: ansible_os_family == 'Debian'
- include_tasks: flatpak.yml
  when: with_flatpak