---
- name: Update and upgrade packages with apt
  apt:
    update_cache: yes
    upgrade: yes
    autoremove: yes
  when: ansible_pkg_mgr == 'apt'

- name: Update and upgrade packages with pacman
  pacman:
    update_cache: yes
    upgrade: yes
  when: ansible_pkg_mgr == 'pacman'

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot
  reboot:
    msg: Rebooting due to a kernel update
  when: reboot_required_file.stat.exists and allow_restart == 'yes'

- name: Install essential packages
  package:
    name: '{{ essential_packages }}'
    state: latest
    update_cache: yes

- name: Set hostname to {{ hostname }}
  hostname:
    name: '{{ hostname }}'

- name: Set timezone to {{ timezone }}
  timezone:
    name: '{{ timezone }}'

- name: Set RAM swappiness
  sysctl:
    name: vm.swappiness
    value: '{{ swappiness }}'
    state: present
    reload: true
  when: swappiness is defined

- name: Enable IP forwarding (ipv4)
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
  when: ip_forward == 'yes'