---
- name: Install Raspberry EEPROM package
  package:
    name:
      - rpi-eeprom
    state: latest

- name: Update EEPROM
  command: rpi-eeprom-update -a
  register: eeprom_update
  changed_when: eeprom_update.rc == 1
  failed_when: eeprom_update.rc != 1 and eeprom_update.rc != 0

- name: Reboot to update EEPROM
  reboot:
  when: eeprom_update.rc == 1 and allow_restart == 'yes'

- name: Enable Ethernet over USB type C
  block:
    - name: Add dwc2 overlay to config.txt
      lineinfile:
        dest: /boot/config.txt
        line: 'dtoverlay=dwc2'
    - name: Add dwc2 modules-load to cmdline.txt
      replace:
        dest: /boot/cmdline.txt
        regexp: 'rootwait(?! \bmodules-load=dwc2,g_ether\b)'
        replace: 'rootwait modules-load=dwc2,g_ether'