---
- name: Set {{ username }} shell to {{ shell }}
  user:
    name: '{{ username }}'
    shell: '{{ shell }}'
    
- name: Give user {{ username }} home folder permissions
  file:
    path: '/home/{{ username }}'
    state: directory
    owner: '{{ username }}'
    group: '{{ username }}'

- name: 'Ensure {{ username }} group exist'
  group:
    name: '{{ username }}'

- name: 'Add docker group'
  group:
    name: docker
  when: with_docker

- name: Ensure login user ({{ username }}) is in docker group
  user:
    name: "{{ username }}"
    groups: 
      - docker
    append: true
  when: with_docker

- name: Check if group wheel exists
  group:
    name: wheel
  register: group_wheel

- name: Setup login user with group wheel
  user:
    name: "{{ username }}"
    groups: 
      - wheel
    append: true
  when: group_wheel.state == 'present'
    
- name: Check if group sudo exists
  group:
    name: sudo
  register: group_sudo

- name: Setup login user with group sudo
  user:
    name: "{{ username }}"
    groups: 
      - sudo
    append: true
  when: group_wheel.state == 'absent' and group_sudo.state == 'present'

- name: Allow {{ username }} user to have passwordless sudo
  template:
    src: passwordless-sudo.j2
    dest: /etc/sudoers.d/passwordless-sudo
    owner: root
    group: root
    mode: 0644
  when: group_wheel.state == 'absent' and group_sudo.state == 'present'