---
- name: Ensure stow is installed
  become: true
  package:
    name:
      - stow
    state: latest

- name: Check if dotfiles folder exists
  stat:
    path: '{{ dotfiles_dir }}'
  register: dotfiles_folder

- name: Clone dotfiles repo
  git:
    repo: '{{ dotfiles_repo }}'
    dest: '{{ dotfiles_dir }}'
  when: not dotfiles_folder.stat.exists

- name: Change dotfiles folder permissions
  file:
    path: '{{ dotfiles_dir}}'
    state: directory
    owner: '{{ username }}'
    group: '{{ username }}'

- name: Stow dotfiles
  shell: 
    cmd: 'stow -v -t /home/{{ username }} --adopt */'
    chdir: '{{ dotfiles_dir }}'
  register: stow_result
  changed_when: '"LINK" in stow_result.stderr'
    
- name: Reset all existing configs to dotfile's
  command: git reset --hard
  args:
    chdir: '{{ dotfiles_dir }}'

- name: Ensure .config/zsh directory exists
  file:
    path: /home/{{ username }}/.config/zsh
    state: directory
  
- name: Download minimal zsh theme
  get_url:
    url: https://raw.githubusercontent.com/subnixr/minimal/master/minimal.zsh
    dest: /home/{{ username }}/.config/zsh/minimal.zsh

- name: Set {{ zsh_mnml_prompt }} as zsh minimal prompt character
  lineinfile:
    dest: /home/{{ username }}/.zshrc
    regexp: '^MNML_USER_CHAR='
    line: "MNML_USER_CHAR={{ zsh_mnml_prompt }}"
    state: present