---
- name: Ensure stow is installed
  become: true
  package:
    name:
      - stow
    state: latest

- name: Clone dotfiles repo (also discard current changes)
  git:
    repo: '{{ dotfiles_repo }}'
    dest: '{{ dotfiles_dir }}'
    force: true

- name: Stow dotfiles
  shell: 
    cmd: 'stow -v -t /home/{{ username }} --adopt */'
    chdir: '{{ dotfiles_dir }}'
  register: stow_result
  changed_when: '"LINK" in stow_result.stderr'

- name: Force update dotfiles repo again
  git:
    repo: '{{ dotfiles_repo }}'
    dest: '{{ dotfiles_dir }}'
    force: true