---
- name: Ensure stow is installed
  become: true
  package:
    name:
      - stow
    state: latest

- name: Clone dotfiles repo (also discard current changes)
  git:
    repo: '{{ dotfiles_repo }}'
    dest: '{{ dotfiles_dir }}'
    force: true

- name: Stow dotfiles
  shell: 
    cmd: 'stow -v -t /home/{{ username }} --adopt */'
    chdir: '{{ dotfiles_dir }}'
  register: stow_result
  changed_when: '"LINK" in stow_result.stderr'

- name: Force update dotfiles repo again
  git:
    repo: '{{ dotfiles_repo }}'
    dest: '{{ dotfiles_dir }}'
    force: true

- name: Ensure .config/zsh directory exists
  file:
    path: /home/{{ username }}/.config/zsh
    state: directory
  
- name: Download minimal zsh theme
  get_url:
    url: https://raw.githubusercontent.com/subnixr/minimal/master/minimal.zsh
    dest: /home/{{ username }}/.config/zsh/minimal.zsh

- name: Ensure .aliases file exists
  file:
    path: /home/{{ username }}/.aliases
    state: touch
    modification_time: preserve
    access_time: preserve

- name: Set {{ zsh_mnml_prompt }} as zsh minimal prompt character
  lineinfile:
    dest: /home/{{ username }}/.aliases
    regexp: '^MNML_USER_CHAR='
    line: "MNML_USER_CHAR={{ zsh_mnml_prompt }}"
    state: present