---
- name: Install required packages
  package:
    name:
      - ca-certificates
      - curl
      - gnupg

- name: Create keyrings folder
  file:
    path: /etc/apt/keyrings
    mode: '0755'
    state: directory

- name: Get gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg

- name: Set key permission
  file: 
    dest: /etc/apt/keyrings/docker.gpg
    mode: a+r

- name: Create docker.list
  template:
    src: templates/docker.list.j2
    dest: /etc/apt/sources.list.d/docker.list

- name: Install Docker
  package:
    name:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: yes