---
- name: Ensure python3-pip is installed
  package:
    name:
      - python3
      - python3-pip
    state: latest

- name: Install docker pip module
  pip:
    name: 
      - docker
      - docker-compose

- name: Pull docker images and launch containers
  community.docker.docker_compose:
    project_src: '{{ containers_dir }}'