---
- name: Copy client/server config file
  become: true
  copy:
    src: '{{ hostname }}.conf'
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: 0644
  notify: restart wireguard