---
- name: Install Wireguard and dependencies with pacman
  become: true
  pacman:
    name: 
      - wireguard-tools
    state: latest
    update_cache: yes

- name: Enable wireguard service
  become: true
  service:
    name: wg-quick@wg0
    enabled: yes